---
title: "Cost of Foodborne Disease in Australia"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This application contain Australian national estimates of burden and cost of foodborne disease, for ten priority pathogens and four sequel illnesses, circa 2019. There are five tabs:

-   **Info**: (Current tab) Provides an overview of the tool and references for further information

-   **Epi Summaries**: Summarises the estimated burden (cases, hospitalisations, and deaths). Can

## Data

The estimates of burden and cost in this app rely on a range of data inputs, some recent, some older. Estimates of burden rely on:

-   Notifications for nationally notifiable pathogens (2019, NNDSS)

-   The water quality study (YYYY, SSS), the second national gastroenteritis survey (YYYY, SSS) and national population estimates (2019, ABS) for non-notifiable diseases

-   Hospitalisation (2019, AIHW)

-   Cause of deaths (2000-2010 CHECK, ABS)


Estimates of cost involve two broad steps. In step one we estimate the number of cost items (e.g. GP visits, doses of medication, time off work) based on burden estimates. In the second step we multiply cost items by unit prices. Data to inform the number of cost items comes from a range of data sources:

-   Mean duration of symptoms and time off work from the second national gastroenteritis survey (YEAR, SOURCE)
-   
-   Expert elicitation (YEAR, REPORT)

Data to inform unit costs come from a range of sources:

-   Statistical value of life (2019, XXX)

-   Medicare benefit values (2019, Medicare)

-   Median income (??)

-   Willingness to avoid pain grief and suffering (YEAR, SOURCE)

-   *Hospitlisation code costs* (YEAR, SOURCE)

-   

